### ISSUE TITLE
Hotspot Error 

### ISSUE THREAD

**Issue by GeoZac** [chaubeyprateek/Hyper_Kernel_Redmi2#1]
On RR 7.1.1 
Getting error on enabling hotspot 
got this fix from RR community https://review.cyanogenmod.org/#/c/175690/

saw this in related 
https://review.cyanogenmod.org/#/c/175662/

looking forward for a new build.

**Comment by chaubeyprateek** [comment]
Fixed

**Comment by GeoZac** [comment]
Thanks for the fix.
